-- 20260826 — the jersey and gear order form
--
-- Replaces the Google Form. Same questions, but the link is per-player, so the
-- three fields that ruin an order — last-name spelling, jersey number, team —
-- arrive pre-filled from our own roster instead of being retyped from a paper
-- worksheet at the kitchen table. The parent confirms rather than transcribes,
-- and anything they change is visible to us as a change.
--
-- The token is a per-player uuid, not the player id: the URL cannot be walked to
-- another family's order by editing a number. It is a capability, not a
-- credential — whoever holds the link can fill in that one player's order and
-- nothing else, which is the right trade for a form parents open on a phone in
-- a gym with no account.
--
-- One row per player, so re-opening the link corrects the order instead of
-- piling up duplicates that someone has to reconcile before ordering.
--
-- Sizes are stored as the exact strings the form offers ("Youth M", "XS/S",
-- '5"'), because the order gets handed to a vendor as text and a lookup table
-- of our own invented codes would only have to be translated back.
--
-- Run: node scripts/run-sql.mjs migrations/20260826_gear_orders.sql
-- Additive and idempotent.

ALTER TABLE public.players
  ADD COLUMN IF NOT EXISTS gear_form_token uuid;

UPDATE public.players
   SET gear_form_token = gen_random_uuid()
 WHERE gear_form_token IS NULL;

ALTER TABLE public.players
  ALTER COLUMN gear_form_token SET DEFAULT gen_random_uuid();

CREATE UNIQUE INDEX IF NOT EXISTS players_gear_form_token_idx
  ON public.players (gear_form_token);

CREATE TABLE IF NOT EXISTS public.player_gear_orders (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id           bigint NOT NULL UNIQUE REFERENCES public.players(id) ON DELETE CASCADE,
  -- As confirmed on the form. Kept separately from the roster columns so a
  -- parent correcting a misspelling doesn't silently rewrite the roster, and so
  -- the order can be read back exactly as the family approved it.
  first_name          text,
  last_name           text,
  jersey_number       text,
  team_name           text,
  jersey_size         text,
  warmup_tee_size     text,
  practice_tee_size   text,
  hoodie_size         text,
  spandex_size        text,
  spandex_length      text,
  jogger_size         text,
  kneepad_size        text,
  sock_size           text,
  arm_sleeve_size     text,
  shoe_size           text,
  worksheet_confirmed boolean NOT NULL DEFAULT false,
  shoe_invoice_ack    boolean NOT NULL DEFAULT false,
  notes               text,
  edited_by           text,
  edited_at           timestamptz,
  submitted_at        timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS player_gear_orders_updated_at ON public.player_gear_orders;
CREATE TRIGGER player_gear_orders_updated_at
  BEFORE UPDATE ON public.player_gear_orders
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE INDEX IF NOT EXISTS player_gear_orders_team_idx ON public.player_gear_orders (team_name);

-- Staff read these in the app. Writes come from the form endpoint under the
-- service role, which bypasses RLS, so no public insert policy is needed and an
-- anonymous client cannot write here directly.
ALTER TABLE public.player_gear_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_gear_orders_approved ON public.player_gear_orders;
CREATE POLICY player_gear_orders_approved ON public.player_gear_orders
  FOR ALL
  USING      (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved))
  WITH CHECK (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved));

ALTER TABLE public.player_gear_orders REPLICA IDENTITY FULL;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
    WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='player_gear_orders') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.player_gear_orders;
  END IF;
END $$;

COMMENT ON COLUMN public.players.gear_form_token IS
  'Unguessable per-player key for the public gear order form. A capability, not a credential.';
