-- 20260823 — Per-player incident and issue log.
--
-- Coaches need somewhere to write down the things that currently live in their
-- heads and in text threads: an injury and how it's tracking, a parent asking
-- about playing time, friction between two players. The point is the HISTORY —
-- the third playing-time conversation with the same family reads very
-- differently from the first, and right now nobody can see that it's the third.
--
-- Keyed to the player, not the team, so the record follows an athlete when she
-- changes teams between seasons. team_name is denormalised alongside it so a
-- report still says which team she was on when it happened, which is the
-- context that makes an old entry legible.
--
-- status is deliberately three-state. 'monitoring' is the honest answer for a
-- healing ankle or a family being watched, and without it everything sits at
-- 'open' forever and the list stops being read.
--
-- Run: node scripts/run-sql.mjs migrations/20260823_player_incidents.sql
-- Additive and idempotent.

CREATE TABLE IF NOT EXISTS public.player_incidents (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id         bigint NOT NULL REFERENCES public.players(id) ON DELETE CASCADE,
  team_name         text   NOT NULL,
  kind              text   NOT NULL,
  summary           text   NOT NULL,
  occurred_on       date   NOT NULL DEFAULT CURRENT_DATE,
  status            text   NOT NULL DEFAULT 'open',
  resolution        text,
  reported_by       text,
  reported_by_email text,
  resolved_by       text,
  resolved_at       timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'player_incidents_kind_chk') THEN
    ALTER TABLE public.player_incidents ADD CONSTRAINT player_incidents_kind_chk
      CHECK (kind IN ('injury','playing_time','player_conflict','parent_concern','behavior','other'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'player_incidents_status_chk') THEN
    ALTER TABLE public.player_incidents ADD CONSTRAINT player_incidents_status_chk
      CHECK (status IN ('open','monitoring','resolved'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS player_incidents_player_idx ON public.player_incidents (player_id, occurred_on DESC);
CREATE INDEX IF NOT EXISTS player_incidents_team_idx   ON public.player_incidents (team_name, status);
CREATE INDEX IF NOT EXISTS player_incidents_open_idx   ON public.player_incidents (status, occurred_on DESC);

DROP TRIGGER IF EXISTS player_incidents_updated_at ON public.player_incidents;
CREATE TRIGGER player_incidents_updated_at
  BEFORE UPDATE ON public.player_incidents
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- Same access model every other table here uses: any approved coach. The app
-- scopes the list to a coach's own teams unless they hold can_view_teams.
ALTER TABLE public.player_incidents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_incidents_all_approved ON public.player_incidents;
CREATE POLICY player_incidents_all_approved ON public.player_incidents
  FOR ALL
  USING      (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved))
  WITH CHECK (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved));

-- Live updates, so a second coach opening the same player sees a new entry
-- without reloading. (public.players spent months off this publication.)
ALTER TABLE public.player_incidents REPLICA IDENTITY FULL;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
     WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='player_incidents'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.player_incidents;
  END IF;
END $$;

COMMENT ON TABLE public.player_incidents IS
  'Injuries, playing-time conversations, player conflicts and parent concerns, logged per player so the history is visible across a season.';
