-- 20260828 — the school games we could read out of what families pasted
--
-- The schedule box on the school-team form says "rough is fine", so what came
-- back is a spreadsheet paste, a bare list of dates, a whole high-school
-- schedule as text, or — for 43 of 78 — a link and nothing else. This table
-- holds only what was actually parsed, so "we don't know" stays visibly
-- different from "no games".
--
-- Rows are keyed to the SCHOOL, not the player: one parent pasting the Sycamore
-- Springs schedule tells us when every DS Elite girl at Sycamore Springs is
-- playing. school_key is the normalised name so "Wimberly" and "Wimberley High
-- School" land together.
--
-- opponent_key is the same normalisation applied to whoever they're playing.
-- That is the whole point of the table: when one school's opponent_key matches
-- another school where we also have players, our girls are playing each other,
-- and a coach wants to know that before she reads about it on Instagram.
--
-- source_report_id keeps the paste it came from, and `raw` the exact line, so a
-- parse that went wrong can always be traced back rather than argued about.
--
-- Rebuilt wholesale by scripts/parse-school-schedules.mjs, so nothing here is
-- hand-edited: fix the family's answer and re-run.
--
-- Run: node scripts/run-sql.mjs migrations/20260828_school_games.sql
-- Additive and idempotent.

CREATE TABLE IF NOT EXISTS public.school_games (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_key       text NOT NULL,
  school_name      text NOT NULL,
  game_date        date NOT NULL,
  end_date         date,
  opponent         text,
  opponent_key     text,
  note             text,
  is_game          boolean NOT NULL DEFAULT true,
  home             boolean,
  venue            text,
  times            text[] NOT NULL DEFAULT '{}',
  level            text,
  raw              text,
  source_report_id bigint REFERENCES public.school_team_reports(id) ON DELETE CASCADE,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS school_games_dedupe_idx
  ON public.school_games (school_key, game_date, coalesce(opponent, ''), coalesce(level, ''));
CREATE INDEX IF NOT EXISTS school_games_date_idx ON public.school_games (game_date);
CREATE INDEX IF NOT EXISTS school_games_opponent_idx ON public.school_games (opponent_key);

ALTER TABLE public.school_games ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS school_games_read ON public.school_games;
CREATE POLICY school_games_read ON public.school_games
  FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved));

ALTER TABLE public.school_games REPLICA IDENTITY FULL;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
    WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='school_games') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.school_games;
  END IF;
END $$;
