-- 20260823 — Admin triage workflow for player incidents.
--
-- Three states were enough for the coach filing a report; they are not enough
-- to run a queue. 'open' conflated "nobody has looked at this yet" with "we are
-- working on it", which is exactly the distinction an admin needs to see at a
-- glance — an untouched report is the only kind that is actually urgent.
--
-- Stages: open (new, unseen) → acknowledged (in review) → monitoring → resolved.
-- Nothing is forced to walk them in order; a scraped knee can go straight from
-- new to resolved.
--
-- assigned_to says who owns it. Without an owner, a queue that several admins
-- can see is a queue nobody picks up.
--
-- player_incident_notes is the running account of what was done. The stage tells
-- you where something is; the notes tell you why, which is what anyone reading
-- this back in six months actually needs.
--
-- Run: node scripts/run-sql.mjs migrations/20260823_incident_workflow.sql
-- Additive and idempotent.

ALTER TABLE public.player_incidents
  ADD COLUMN IF NOT EXISTS assigned_to     text,
  ADD COLUMN IF NOT EXISTS acknowledged_at timestamptz,
  ADD COLUMN IF NOT EXISTS acknowledged_by text,
  ADD COLUMN IF NOT EXISTS notified_at     timestamptz;

ALTER TABLE public.player_incidents DROP CONSTRAINT IF EXISTS player_incidents_status_chk;
ALTER TABLE public.player_incidents ADD CONSTRAINT player_incidents_status_chk
  CHECK (status IN ('open','acknowledged','monitoring','resolved'));

CREATE TABLE IF NOT EXISTS public.player_incident_notes (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id  bigint NOT NULL REFERENCES public.player_incidents(id) ON DELETE CASCADE,
  note         text   NOT NULL,
  -- Set when the note records a stage change, so the thread reads as a history
  -- rather than as loose comments.
  stage_from   text,
  stage_to     text,
  author       text,
  author_email text,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS player_incident_notes_idx ON public.player_incident_notes (incident_id, created_at);

ALTER TABLE public.player_incident_notes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS player_incident_notes_all_approved ON public.player_incident_notes;
CREATE POLICY player_incident_notes_all_approved ON public.player_incident_notes
  FOR ALL
  USING      (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved))
  WITH CHECK (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved));

ALTER TABLE public.player_incident_notes REPLICA IDENTITY FULL;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
     WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='player_incident_notes'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.player_incident_notes;
  END IF;
END $$;

COMMENT ON COLUMN public.player_incidents.notified_at IS
  'When the admin alert for this report went out. NULL means the alert never fired — worth noticing.';
