-- 20260824 — "Did you make a school team?"
--
-- Asking 166 families to reply by email means 166 replies to read, re-type and
-- inevitably lose. A one-per-player link writes the answer straight into a table
-- instead, and the same link works as an edit link when a girl moves up from JV
-- mid-season.
--
-- The token is a per-player uuid rather than the player id, so the URL cannot be
-- walked to somebody else's form by changing a number. It is a capability, not a
-- credential: anyone holding the link can fill in that one player's row and
-- nothing else. That is the right trade for a form parents must be able to open
-- from a phone without an account.
--
-- One row per player, so re-submitting corrects the answer rather than piling up
-- duplicates that someone has to reconcile.
--
-- Run: node scripts/run-sql.mjs migrations/20260824_school_team_reports.sql
-- Additive and idempotent.

ALTER TABLE public.players
  ADD COLUMN IF NOT EXISTS school_form_token uuid;

UPDATE public.players
   SET school_form_token = gen_random_uuid()
 WHERE school_form_token IS NULL;

ALTER TABLE public.players
  ALTER COLUMN school_form_token SET DEFAULT gen_random_uuid();

CREATE UNIQUE INDEX IF NOT EXISTS players_school_form_token_idx
  ON public.players (school_form_token);

CREATE TABLE IF NOT EXISTS public.school_team_reports (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id    bigint NOT NULL UNIQUE REFERENCES public.players(id) ON DELETE CASCADE,
  made_team    boolean,
  school       text,
  grade        text,
  team_level   text,
  schedule     text,
  notes        text,
  submitted_at timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS school_team_reports_updated_at ON public.school_team_reports;
CREATE TRIGGER school_team_reports_updated_at
  BEFORE UPDATE ON public.school_team_reports
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE INDEX IF NOT EXISTS school_team_reports_school_idx ON public.school_team_reports (school);

-- Coaches read these in the app. Writes come from the form endpoint under the
-- service role, which bypasses RLS — so no public insert policy is needed and
-- the table is not writable by an anonymous client directly.
ALTER TABLE public.school_team_reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS school_team_reports_read_approved ON public.school_team_reports;
CREATE POLICY school_team_reports_read_approved ON public.school_team_reports
  FOR ALL
  USING      (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved))
  WITH CHECK (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved));

ALTER TABLE public.school_team_reports REPLICA IDENTITY FULL;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables
    WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='school_team_reports') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.school_team_reports;
  END IF;
END $$;

COMMENT ON COLUMN public.players.school_form_token IS
  'Unguessable per-player key for the public school-team form. A capability, not a credential.';
