-- 20260828 — the schedules we fetched ourselves
--
-- 43 of 78 families answered the schedule question with a link. Most of those
-- links are public and machine-readable once you ask for them properly: a Google
-- Sheet has a CSV export, a Google Doc has a text export, a school site is just
-- HTML. This table is what came back, one row per URL.
--
-- Kept separate from school_team_reports on purpose. The family's answer is
-- theirs and shouldn't be overwritten with something we scraped, and a fetch
-- that goes stale (a school reposts its schedule) has to be re-runnable without
-- touching what they wrote.
--
-- `text` is the extracted plain text, parsed by the same code that reads what
-- families paste. `status` records fetches that came back empty or unreadable so
-- a page that needs a human is visible rather than silently missing.
--
-- Run: node scripts/run-sql.mjs migrations/20260828_school_schedule_sources.sql
-- Additive and idempotent.

CREATE TABLE IF NOT EXISTS public.school_schedule_sources (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_key   text NOT NULL,
  school_name  text NOT NULL,
  url          text NOT NULL UNIQUE,
  fetch_url    text,
  kind         text,
  status       text NOT NULL DEFAULT 'pending',
  http_status  integer,
  text         text,
  games_found  integer NOT NULL DEFAULT 0,
  note         text,
  fetched_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS school_schedule_sources_school_idx
  ON public.school_schedule_sources (school_key);

ALTER TABLE public.school_schedule_sources ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS school_schedule_sources_read ON public.school_schedule_sources;
CREATE POLICY school_schedule_sources_read ON public.school_schedule_sources
  FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved));
