-- 20260826 — remember which clinic reminders already went out
--
-- The daily clinic reminder is a digest: one message per coach per day covering
-- everything she's on today and tomorrow. Vercel Cron is at-least-once and the
-- endpoint is also hittable by hand, so without a record of what was sent, a
-- retry means a coach gets told about tonight's clinic twice.
--
-- Keyed on (coach_email, for_date) — the day the digest covers — so a re-run on
-- the same day is a no-op and the next day sends normally. `items` keeps what
-- was actually said, which is the difference between "we reminded her" and "we
-- think we reminded her" when somebody doesn't turn up.
--
-- Run: node scripts/run-sql.mjs migrations/20260826_clinic_reminder_log.sql
-- Additive and idempotent.

CREATE TABLE IF NOT EXISTS public.clinic_reminder_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coach_email text NOT NULL,
  coach_name  text,
  for_date    date NOT NULL,
  items       jsonb NOT NULL DEFAULT '[]'::jsonb,
  emailed     boolean NOT NULL DEFAULT false,
  pushed      integer NOT NULL DEFAULT 0,
  sent_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (coach_email, for_date)
);

CREATE INDEX IF NOT EXISTS clinic_reminder_log_date_idx ON public.clinic_reminder_log (for_date DESC);

-- Written only by the cron endpoint under the service role. Approved coaches can
-- read it so "did she get told?" is answerable in the app.
ALTER TABLE public.clinic_reminder_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS clinic_reminder_log_read ON public.clinic_reminder_log;
CREATE POLICY clinic_reminder_log_read ON public.clinic_reminder_log
  FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved));
