-- 20260831 — parent photo uploads.
--
-- Families take the good photos. They currently arrive as texts to a coach, in
-- SportsYou threads, and in a group chat nobody can search three weeks later,
-- so the club has no library and Anna has nothing to post.
--
-- A per-family link, the same shape as the gear form: bookmark it once, open it
-- from a phone at a tournament, pick the event, choose a dozen photos, done. No
-- login, because a parent standing in a convention centre will not make one.
--
-- WHAT MAKES A PHOTO FINDABLE
--
-- Everything hangs off the event. A photo with a team and a tournament against
-- it can be found by either; a folder of IMG_4471.HEIC cannot be found at all.
-- The tournament is picked from that team's own schedule rather than typed, so
-- twelve families cannot produce nine spellings of "Lone Star Classic".
--
-- THE BUCKET IS PRIVATE
--
-- These are photographs of children. Nothing is served from a public URL; the
-- app mints a short-lived signed link when staff open the library. Uploads go
-- straight from the browser to Supabase on a signed URL, never through our own
-- API — Vercel caps a request body at 4.5MB and an iPhone photo is routinely
-- bigger than that, so proxying them would fail on the first real upload.
--
-- Run: node scripts/run-sql.mjs migrations/20260831_team_photos.sql
-- Additive and idempotent.

-- ── Bucket ──────────────────────────────────────────────────────────────────
-- 25MB covers an iPhone burst frame with room to spare. HEIC is listed because
-- that is what an iPhone actually sends unless the owner has changed a setting
-- they do not know exists.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('team-photos', 'team-photos', false, 26214400,
        ARRAY['image/jpeg','image/png','image/heic','image/heif','image/webp','image/gif','video/mp4','video/quicktime'])
ON CONFLICT (id) DO UPDATE
  SET file_size_limit = EXCLUDED.file_size_limit,
      allowed_mime_types = EXCLUDED.allowed_mime_types;

-- ── Per-family upload link ──────────────────────────────────────────────────
ALTER TABLE public.players
  ADD COLUMN IF NOT EXISTS photo_upload_token uuid;

UPDATE public.players
   SET photo_upload_token = gen_random_uuid()
 WHERE photo_upload_token IS NULL;

ALTER TABLE public.players
  ALTER COLUMN photo_upload_token SET DEFAULT gen_random_uuid();

CREATE UNIQUE INDEX IF NOT EXISTS players_photo_upload_token_idx
  ON public.players (photo_upload_token);

COMMENT ON COLUMN public.players.photo_upload_token IS
  'Per-family capability token for /photos?t=… . Meant to be bookmarked and reused all season, so it is never rotated casually.';

-- ── One row per uploaded photo ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.player_photos (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  storage_path   text        NOT NULL UNIQUE,
  -- Who sent it, and therefore which team it belongs to. Denormalised because
  -- a girl can change teams and the photo stays where it was taken.
  player_id      bigint      REFERENCES public.players(id) ON DELETE SET NULL,
  team_name      text,
  uploaded_by    text,                       -- as the parent typed it
  -- Where it is from. context is the coarse bucket; tournament_id is set only
  -- when context = 'tournament'.
  context        text        NOT NULL DEFAULT 'other',   -- tournament | practice | team_event | other
  tournament_id  bigint      REFERENCES public.tournaments(id) ON DELETE SET NULL,
  event_label    text,                       -- resolved name, kept so a deleted tournament doesn't orphan the caption
  taken_on       date,
  caption        text,
  original_name  text,
  content_type   text,
  size_bytes     bigint,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS player_photos_team_idx    ON public.player_photos (team_name, created_at DESC);
CREATE INDEX IF NOT EXISTS player_photos_tourn_idx   ON public.player_photos (tournament_id);
CREATE INDEX IF NOT EXISTS player_photos_player_idx  ON public.player_photos (player_id);

COMMENT ON TABLE public.player_photos IS
  'Photos sent in by families. The file lives in the private team-photos bucket; this row is what makes it findable.';

ALTER TABLE public.player_photos ENABLE ROW LEVEL SECURITY;

-- Any approved coach can see and manage the library. The upload form writes
-- with the service role, past RLS, because families have no account.
DROP POLICY IF EXISTS player_photos_all_approved ON public.player_photos;
CREATE POLICY player_photos_all_approved ON public.player_photos
  FOR ALL
  USING      (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved))
  WITH CHECK (EXISTS (SELECT 1 FROM public.coaches c WHERE c.id = auth.uid() AND c.is_approved));
